### ISSUE TITLE
When entering pip this error is occuring

### ISSUE THREAD

**Issue by ragul-pr** [harshitverma209/android_pip#7]
----------------FIREBASE CRASHLYTICS----------------
I/flutter (11285): PlatformException(error, Activity must be resumed to enter picture-in-picture, null, java.lang.IllegalStateException: Activity must be resumed to enter picture-in-picture
I/flutter (11285):      at android.app.Activity.enterPictureInPictureMode(Activity.java:2984)
I/flutter (11285):      at com.thesparks.android_pip.AndroidPIPModePlugin.onMethodCall(AndroidPIPModePlugin.kt:102)
I/flutter (11285):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
I/flutter (11285):      at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
I/flutter (11285):      at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
I/flutter (11285):      at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter (11285):      at android.os.Handler.handleCallback(Handler.java:958)
I/flutter (11285):      at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter (11285):      at android.os.Looper.loopOnce(Looper.java:205)
I/flutter (11285):      at android.os.Looper.loop(Looper.java:294)
I/flutter (11285):      at android.app.ActivityThread.main(Ac
I/flutter (11285): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
I/flutter (11285): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
I/flutter (11285): <asynchronous suspension>
I/flutter (11285): #2      AndroidPIP.enterPipMode (package:android_pip/android_pip.dart:57:9)
I/flutter (11285): <asynchronous suspension>
I/flutter (11285): ------------------------------

**Comment by harshitverma209** [comment]
Hi Ragul, please share a minimal reproducible sample for me to run.

**Comment by ragul-pr** [comment]
it is while entering into pip by calling enter pip method. I am using google pixel 8 pro android 14 emulator for checking this issue.

**Comment by harshitverma209** [comment]
Thanks Ragul, but by a minimal reproducible sample, I mean a piece of code that would directly run as a flutter app.

**Comment by ragul-pr** [comment]
oh but it takes a lot of time to seperate the pip code from my whole project. I will try running the example project.

**Comment by harshitverma209** [comment]
You don't really need to do that. You can create a new scratch project and use the package in it. This helps us make sure that something is wrong with this package and not some other package/code that might be conflicting. Also, it would help me pinpoint the issue.

**Comment by ragul-pr** [comment]
Actually the example code is working good.

**Comment by harshitverma209** [comment]
That means it's not a problem with the package itself. Still, I would be able to help if you can share a sample in which the issue is occurring.

**Comment by ragul-pr** [comment]
Is it possible for you join me over a google meet call. because I can't share this code. Most propably this code has some conflicts which may be the reason for error

**Comment by ragul-pr** [comment]
Can you please get back to me fast. Its an urgent fix.

**Comment by harshitverma209** [comment]
Hi Ragul, please do not share your organization code. What I mean by a sample is a piece of code which has the same issue as the one you are mentioning and is a complete flutter app.

**Comment by ragul-pr** [comment]
It will take a lot of time. because I can't understand where it goes wrong.
